apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: block-buster-ingress
  namespace: dev-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: dev-demo.arp-tech.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: block-buster-service
                port: 
                  number: 80